@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	BvNativeFadeActive
	.type	 BvNativeFadeActive,function
	.thumb_func
BvNativeFadeActive:
	ldr	r0, .L5
	ldrb	r0, [r0, #7]
	lsr	r0, r0, #7
	bx	lr
.L6:
	.align	2, 0
.L5:
	.word	gPaletteFade
.Lfe1:
	.size	 BvNativeFadeActive,.Lfe1-BvNativeFadeActive
