#!/usr/bin/env python3
"""Regenerate the review from exact committed emulator captures."""
from pathlib import Path
import json,base64,html,hashlib
r=Path(__file__).resolve().parents[1];o=r/'docs/review';o.mkdir(exist_ok=True)
new='eaf073d434a9347dfc2ed921f5f44d163563964b';old='f3514caa05d99ff60c0c666d017fced8274e11e9';n02='dec2c5e479cdceedf8b358d00448358640561b91';n03='b530fa661254c2c4b5ef1d75ce4010c2d5d741ec'
cards=[]
def frame(path,label,commit):
 p=r/path;assert p.is_file();return {'path':path,'label':label,'tested_commit':commit,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
def pair(title,description,left,right):cards.append({'title':title,'description':description,'frames':[left,right]})
rooms=[('entrance','The entrance','Worn stone, rubble and framed stairs replace the repeated tile grid. The note and supply box remain in their tested positions.'),('landing','The Quiet Landing','A warm recovery area and practice alcove give the guide and trial distinct places. The cleared trial now leaves a small remains marker.'),('service','The Service Room','Cool service tiles, conduits, a workbench, tag bag and cache give the quest and preparation route visible landmarks.'),('gauntlet','The gauntlet','Supports and floor wear frame the patrol route. Cleared encounters remain visibly resolved when revisiting.'),('boss','The gate chamber','Warm masonry and supports stage the warden. The northeast gate and supply line reflect victory and preparation.'),('exit','The overlook','A quiet review space has its own floor composition and small northern alcove. The completed slice remains saveable and returnable.')]
for slug,title,desc in rooms:
 pair(title,desc,frame(f'docs/evidence/n01/before/{slug}-center.png','Before environment work · completed-save revisit',old),frame(f'docs/evidence/n05/final/rooms/{slug}-center.png','Current build · same room position and facing',new))
pair('The trap communicates its state','Two captures from the current build at the same position: the live wire has an amber core and sparks; the spent wire is quiet and broken. Repeat traversal causes no second damage, and the spent state survives a cold reload.',frame('docs/evidence/n05/final/wire-pair/wire-live-clear.png','Current: live wire',new),frame('docs/evidence/n05/final/wire-pair/wire-spent-clear.png','Current: spent wire',new))
pair('An opened cache stays open','Before, a successful CHARGE interaction left a sealed-looking box. Now the open cache reflects its persistent reward flag. Cancelling or lacking inventory space keeps it sealed.',frame('docs/evidence/n02/final/craft-blast-use/blasted.png','Before state feedback · successful cache interaction',n02),frame('docs/evidence/n05/final/craft-blast-use/blasted.png','Current · successful cache interaction',new))
pair('A locked gate looks locked','The old arch looked open before the required fights. The new bars match the gameplay restriction, then open after victory. These are both pre-victory captures.',frame('docs/evidence/n02/final/gates/boss-locked.png','Before state feedback · progression still locked',n02),frame('docs/evidence/n05/final/gates/boss-locked.png','Current · progression still locked',new))
pair('Repeat recovery takes one page','The old guide held control for extra advice after recovery. Repeat visits now use one contextual page: the trial hint before victory, the west ladder afterwards. Full first-use teaching and free recovery are unchanged.',frame('docs/evidence/n05/before-readable/after-two-presses.png','Before · extra advice after two A presses',n03),frame('docs/evidence/n05/final/guide-after-trial/recovery-result.png','Current · recovery and next direction in one page',new))
pair('Recovery leads back to victory','All six exact ordinary defeat saves reach victory and preserve it through manual save and cold reload. These two frames show the Carl-down case, not a newly invented or edited save.',frame('docs/evidence/n05/recovery/carl-down-win/won-clear.png','Current · victory after recovered Carl-down loss',new),frame('docs/evidence/n05/recovery/carl-down-cold/cold-victory.png','Current · same victory after cold reload',new))
manifest={'date':'2026-10-06','tested_commit':new,'merged_commit':'f2edec341fe1a1900f82740cbef25563b08f7532','production_sha256':'8e7e8c20c8dde66488d9374ec90e80391a02c255ad4a0a422e7392f04f1ccfb6','capture_method':'Actual unedited 240x160 mGBA output. CSS scales with nearest-neighbor; no painted or generated game captures. Source paths and exact byte hashes below.','cards':cards}
(o/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
parts=[]
for i,c in enumerate(cards):
 figs=[]
 for f in c['frames']:
  encoded=base64.b64encode((r/f['path']).read_bytes()).decode()
  figs.append(f'<figure><img width="480" height="320" src="data:image/png;base64,{encoded}" alt="{html.escape(c["title"]+": "+f["label"],quote=True)}"><figcaption>{html.escape(f["label"])}<small>Tested {f["tested_commit"][:7]} · {html.escape(Path(f["path"]).name)}</small></figcaption></figure>')
 parts.append(f'<section id="view-{i}"><h2>{html.escape(c["title"])}</h2><p>{html.escape(c["description"])}</p><div class="pair">'+''.join(figs)+'</div></section>')
page='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DungeonCrawlerCarlemon — overnight playtest review</title><style>
:root{color-scheme:dark;background:#111817;color:#e9ede8;font-family:system-ui,sans-serif}body{max-width:1024px;margin:0 auto;padding:32px 24px 64px;line-height:1.6}h1{font-size:clamp(28px,5vw,44px);line-height:1.15;max-width:850px;margin:14px 0 20px}h2{font-size:25px;line-height:1.25;margin:0 0 10px}p{max-width:860px;color:#c6d1c9}a{color:#a7dbba}header{padding:20px 0 36px;border-bottom:1px solid #394b42}.eyebrow{font-size:13px;letter-spacing:.12em;text-transform:uppercase;color:#b5c695}.lead{font-size:19px}nav{display:flex;gap:22px;flex-wrap:wrap}section{padding:38px 0;border-bottom:1px solid #394b42}.pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;margin-top:22px}figure{margin:0}img{display:block;width:100%;height:auto;image-rendering:pixelated;background:#080d0c;border:1px solid #394b42;box-sizing:border-box}figcaption{margin-top:10px;font-size:14px}small{display:block;color:#9baa9f;font-size:12px;margin-top:4px}li{margin:8px 0}code{overflow-wrap:anywhere;font-size:13px}details{border:1px solid #394b42;padding:18px;margin-top:24px}summary{cursor:pointer;font-weight:600}.badge{display:inline-block;padding:5px 11px;margin-top:10px;background:#253b2d;border:1px solid #45674e;color:#cfe8cf;border-radius:4px}@media(max-width:620px){body{padding:20px 16px}.pair{grid-template-columns:1fr;gap:22px}section{padding:28px 0}}
</style></head><body><header><div class="eyebrow">Private playtest review · 6 October 2026</div><h1>A more readable, inhabited dungeon</h1><p class="lead">Six rooms now have distinct materials and useful landmarks. Traps, caches, gates and cleared encounters show what has changed. Repeat recovery is quicker.</p><p>These are actual emulator captures. The six room comparisons use matched positions and facing; state comparisons are labeled separately. Approved Carl, Donut and living enemy artwork remains unchanged.</p><nav><a href="#view-0">Room comparisons</a><a href="#view-6">Visible game states</a><a href="#play">Play the slice</a><a href="#evidence">Checks and limits</a></nav><span class="badge">Stages 0–5 verified · ready for your playtest</span></header>'''+''.join(parts)+'''
<section id="play"><h2>Play the slice</h2><p>Extract the private ZIP and open <strong>DungeonCrawlerCarlemon-N05.gba</strong> in a GBA emulator. The tested core is mGBA 0.10.5. Start a fresh save; keep older development saves separately.</p><ul><li>D-pad moves. A interacts/confirms. B cancels. START opens the menu; save outside battle.</li><li>Read the entrance note, then visit the Quiet Landing guide and trial. Carl uses STRIKE/BRACE; Donut uses SPARK/WEAKEN.</li><li>The guide restores health, status and action uses freely. Defeat recovers locally; retry or backtrack.</li><li>The Service Room's southwest ladder leads to two patrols and the warden. After winning the required fights, examine the northeast stairs.</li><li>The quest, trap, equipment and cache preparation are optional. BRACE/WEAKEN or the cache preparation route can help with the warden.</li></ul><p>Please report confusing directions, collisions, unreadable text/art, reward or save inconsistencies, and your actual completion time. The full floor waits for your feedback.</p></section>
<section id="evidence"><h2>What was verified</h2><p>The final production build passed 90 actual emulator sessions and 1,531 assertions: 1,338 production checks and 193 explicitly labeled diagnostic-fixture checks. All 90 emulator error logs were empty. There are also 38 exact rendered comparisons.</p><p>Coverage includes fresh prepared completion, both patrol orders, segmented unprepared victory, all six exact recovered-save wins and cold reloads, quest/reward/crafting branches, old-save compatibility, and blocked collection paths.</p><p><strong>Still for human review:</strong> pacing and the 20–30 minute target. Scripted waits are not reading or decision time. Prepared uninterrupted completion passes; unprepared wins are verified separately, not claimed as an uninterrupted run.</p><p><strong>Remaining placeholders:</strong> static poses, stationary Donut, inherited audio and some interface/effect elements. Opening chronology is compressed with original adaptation dialogue. The accepted environment kit has documented source-sheet/packed-output omissions; complete source-sheet reproduction is not claimed.</p><details><summary>Source, checksum and review evidence</summary><p>Tested source <code>eaf073d434a9347dfc2ed921f5f44d163563964b</code><br>Merged as <code>f2edec341fe1a1900f82740cbef25563b08f7532</code></p><p>Production SHA256<br><code>8e7e8c20c8dde66488d9374ec90e80391a02c255ad4a0a422e7392f04f1ccfb6</code></p><p><a href="https://github.com/12nuskek/DungeonCrawlerCarlemon/tree/005154eef04e24318d48b6435087e1c6954cff42/docs/evidence/n05">Complete build/runtime logs and capture provenance</a> · <a href="https://github.com/12nuskek/DungeonCrawlerCarlemon/pull/50">Verified final change</a></p><p>The review ZIP contains the production ROM, this offline visual review, build/play instructions and selected evidence. No diagnostic ROMs, edited saves or public playable release. The bundled manifest identifies every capture and its byte hash.</p></details></section></body></html>
'''
(o/'index.html').write_text(page)
print(len(cards),'comparison cards;',len(page),'HTML bytes')
